'''errors and exceptions types of errors /exceptions
try-blocks except finally rasing exception built in function'''
#handling zero division error
'''num=int(input("enter the numerator:"))
deno=int(input("enter the denomenator:"))
try:
    quo=num/deno
    print("Quotient:",quo)
except ZeroDivisionError:
    print("denominator cannnot be zero")'''


#multiple exception handling
'''try:
    num=int(input("enter a number:"))
    print(num**2)
except (KeyboardInterrupt):
    print("You have to enter a number.... progrm")
except (ValueError):
    print("please check before you enter... program")
print("Bye")'''


#multiple exception in a single block handling
'''try:
    num=int(input("enter a number:"))
    print(num**2)
except(KeyboardInterrupt,ValueError,TypeError):
    print("please check before entering..progrm error")'''

#raise an exception
'''try:
    num=4
    print(num)
    raise ValueError
except:
    print("even excuting perfectly...exception")'''


#re-raise an error
'''try:
    raise NameError
except:
    print("re-raise")
    raise'''


#instance using in exceptons 
try:
    raise Exception('hi','students')
except Exception as errorObj:
    print(type(errorObj))
    print(errorObj.args)
    print(errorObj)
    x,y=errorObj.args
    print("Assigned1:",x)
    print("Assigned2:",y)

